### ISSUE TITLE
IP Keeps Changing Constantly

### ISSUE THREAD

**Issue by magicstone1412** [Mon-ius/Docker-Warp-Socks#40]
Thank you for creating a well-optimized Docker version for use.  

After using it for a while, I noticed that some versions (v3, v4) have an issue where the IP keeps changing constantly. I'm not sure what is causing this issue. Currently, I am using the following Docker YAML file:  

```yaml
---
services:
  warp-socks:
    image: monius/docker-warp-socks:v3
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /lib/modules:/lib/modules
    environment:
      - WARP_LICENSE=$WARP_LICENSE
      - NET_PORT=9091
    ports:
      - 9091:9091
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5
```

Could you please provide me with some advice on this matter? Thank you!
